prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

SELECT ?type
WHERE {
	?type rdf:type owl:Class
	NOT EXISTS {
		?subtype rdfs:subClassOf ?type
		FILTER(?subtype != ?type)
	}
}